/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu May 19 11:02:53 CEST 2022
 * Generated source version: 2.2.2
 * 
 */

public final class OperatoreDipendente_OperatoreDipendenteCXFImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://opessan.opessanws.services.csi.it/", "OperatoreDipendente");

    private OperatoreDipendente_OperatoreDipendenteCXFImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = OperatoreDipendente.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OperatoreDipendente ss = new OperatoreDipendente(wsdlURL, SERVICE_NAME);
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.OperatoreDipendente port = ss.getOperatoreDipendenteCXFImplPort();  
        

        {
        System.out.println("Invoking getDettaglioConf...");
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConf.Arg0 _getDettaglioConf_arg0 = null;
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConfResponse2.Return _getDettaglioConf__return = port.getDettaglioConf(_getDettaglioConf_arg0);
        System.out.println("getDettaglioConf.result=" + _getDettaglioConf__return);


        }

        System.exit(0);
    }

}
