
/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente;

import java.util.logging.Logger;


/**
 * This class was generated by Apache CXF 2.2.2
 * Thu May 19 11:02:53 CEST 2022
 * Generated source version: 2.2.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "OperatoreDipendente",
                      portName = "OperatoreDipendenteCXFImplPort",
                      targetNamespace = "http://opessan.opessanws.services.csi.it/",
                      wsdlLocation = "https://tst-applogic.reteunitaria.piemonte.it:1449/opessanwsj/services/operatoreDipendenteUserTkn?wsdl",
                      endpointInterface = "it.csi.def.opessanws.opessan.OperatoreDipendente")
                      
public class OperatoreDipendenteImpl implements OperatoreDipendente {

    private static final Logger LOG = Logger.getLogger(OperatoreDipendenteImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.def.opessanws.opessan.OperatoreDipendente#getDettaglioConf(it.csi.def.opessanws.opessan.GetDettaglioConf.Arg0  arg0 )*
     */
    public it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConfResponse2.Return getDettaglioConf(it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConf.Arg0 arg0) { 
        LOG.info("Executing operation getDettaglioConf");
        System.out.println(arg0);
        try {
        	it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConfResponse2.Return _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
