/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu May 19 11:02:53 CEST 2022
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://opessan.opessanws.def.csi.it/", name = "OperatoreDipendente")
@XmlSeeAlso({it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.common.response.ObjectFactory.class,it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.common.request.ObjectFactory.class,ObjectFactory.class})
public interface OperatoreDipendente {

    @WebMethod
    @RequestWrapper(localName = "getDettaglioConf", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConf")
    @ResponseWrapper(localName = "getDettaglioConfResponse", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConfResponse2")
    @WebResult(name = "return", targetNamespace = "")
    public it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConfResponse2.Return getDettaglioConf(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatoreDipendente.GetDettaglioConf.Arg0 arg0
    );

}
