
/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.aura.findprofilianagrafici;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Oct 28 15:14:11 CEST 2011
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "AnagrafeFind", 
                  wsdlLocation = "https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeFind.cls?wsdl=1",
                  targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it") 
public class AnagrafeFind extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFind");
    public final static QName AnagrafeFindSoap = new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFindSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeFind.cls?wsdl=1");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeFind.cls?wsdl=1");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AnagrafeFind(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AnagrafeFind(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagrafeFind() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap() {
        return super.getPort(AnagrafeFindSoap, AnagrafeFindSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap(WebServiceFeature... features) {
        return super.getPort(AnagrafeFindSoap, AnagrafeFindSoap.class, features);
    }

}
