/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.aura.findprofilianagrafici;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Oct 28 15:14:11 CEST 2011
 * Generated source version: 2.2.6
 * 
 */

public final class AnagrafeFindSoap_AnagrafeFindSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFind");

    private AnagrafeFindSoap_AnagrafeFindSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AnagrafeFind.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AnagrafeFind ss = new AnagrafeFind(wsdlURL, SERVICE_NAME);
        AnagrafeFindSoap port = ss.getAnagrafeFindSoap();  
        
        {
        System.out.println("Invoking findProfiliAnagrafici...");
        FindProfiliAnagraficiRequest _findProfiliAnagrafici_profiliRequest = null;
        DatiAnagraficiMsg _findProfiliAnagrafici__return = port.findProfiliAnagrafici(_findProfiliAnagrafici_profiliRequest);
        System.out.println("findProfiliAnagrafici.result=" + _findProfiliAnagrafici__return);


        }

        System.exit(0);
    }

}
