/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.solconfig.configuratoreweb.wsdl.aura.findprofilianagrafici;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Oct 28 15:14:11 CEST 2011
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it", name = "AnagrafeFindSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AnagrafeFindSoap {

    @WebResult(name = "FindProfiliAnagraficiResult", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "FindProfiliAnagrafici", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it", className = "it.csi.solconfig.configuratoreweb.wsdl.aura.FindProfiliAnagrafici")
    @ResponseWrapper(localName = "FindProfiliAnagraficiResponse", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it", className = "it.csi.solconfig.configuratoreweb.wsdl.aura.FindProfiliAnagraficiResponse")
    @WebMethod(operationName = "FindProfiliAnagrafici", action = "http://AnagrafeFind.central.services.auraws.aura.csi.it/AURA.WS.AnagrafeFind.FindProfiliAnagrafici")
    public DatiAnagraficiMsg findProfiliAnagrafici(
        @WebParam(name = "profiliRequest", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it")
                FindProfiliAnagraficiRequest profiliRequest
    );
}
