/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.solconfig.configuratoreweb.wsdl.aura.getprofilosanitario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Sat Nov 19 12:21:05 CET 2011
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", name = "AnagrafeSanitariaSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AnagrafeSanitariaSoap {

    @WebResult(name = "GetProfiloSanitarioResult", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "GetProfiloSanitario", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", className = "it.csi.solconfig.configuratoreweb.wsdl.aura.getprofilosanitario.GetProfiloSanitario")
    @ResponseWrapper(localName = "GetProfiloSanitarioResponse", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", className = "it.csi.solconfig.configuratoreweb.wsdl.aura.getprofilosanitario.GetProfiloSanitarioResponse")
    @WebMethod(operationName = "GetProfiloSanitario", action = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it/AURA.WS.AnagrafeSanitaria.GetProfiloSanitario")
    public SoggettoAuraMsg getProfiloSanitario(
        @WebParam(name = "AURAid", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it")
        java.lang.String aurAid
    );
}
