/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;



/**
 * This class was generated by Apache CXF 2.2.2
 * Thu May 19 09:17:03 CEST 2022
 * Generated source version: 2.2.2
 * 
 */

public final class GetDettaglioOperatore_GetDettaglioOperatoreCXFImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://opessan.opessanws.services.csi.it/", "GetDettaglioOperatore");

    private GetDettaglioOperatore_GetDettaglioOperatoreCXFImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GetDettaglioOperatore.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetDettaglioOperatore ss = new GetDettaglioOperatore(wsdlURL, SERVICE_NAME);
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetDettaglioOperatore port = ss.getGetDettaglioOperatoreCXFImplPort();  
        
        {
        System.out.println("Invoking getInfoOperatoreConf...");
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConf.Arg0 _getInfoOperatoreConf_arg0 = null;
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConfResponse.Return _getInfoOperatoreConf__return = port.getInfoOperatoreConf(_getInfoOperatoreConf_arg0);
        System.out.println("getInfoOperatoreConf.result=" + _getInfoOperatoreConf__return);


        }
        {
        System.out.println("Invoking getInfoOperatore...");
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatore.Arg0 _getInfoOperatore_arg0 = null;
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreResponse.Return _getInfoOperatore__return = port.getInfoOperatore(_getInfoOperatore_arg0);
        System.out.println("getInfoOperatore.result=" + _getInfoOperatore__return);


        }

        System.exit(0);
    }

}
