
/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu May 19 09:17:03 CEST 2022
 * Generated source version: 2.2.2
 * 
 */


@WebServiceClient(name = "GetDettaglioOperatore", 
                  wsdlLocation = "https://tst-applogic.reteunitaria.piemonte.it:1449/opessanwsj/services/getDettaglioOperatoreUserTkn?wsdl",
                  targetNamespace = "http://opessan.opessanws.services.csi.it/") 
public class GetDettaglioOperatore extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://opessan.opessanws.services.csi.it/", "GetDettaglioOperatore");
    public final static QName GetDettaglioOperatoreCXFImplPort = new QName("http://opessan.opessanws.services.csi.it/", "GetDettaglioOperatoreCXFImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-applogic.reteunitaria.piemonte.it:1449/opessanwsj/services/getDettaglioOperatoreUserTkn?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://tst-applogic.reteunitaria.piemonte.it:1449/opessanwsj/services/getDettaglioOperatoreUserTkn?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GetDettaglioOperatore(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetDettaglioOperatore(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetDettaglioOperatore() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns GetDettaglioOperatore
     */
    @WebEndpoint(name = "GetDettaglioOperatoreCXFImplPort")
    public it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetDettaglioOperatore getGetDettaglioOperatoreCXFImplPort() {
        return super.getPort(GetDettaglioOperatoreCXFImplPort, it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetDettaglioOperatore.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDettaglioOperatore
     */
    @WebEndpoint(name = "GetDettaglioOperatoreCXFImplPort")
    public it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetDettaglioOperatore getGetDettaglioOperatoreCXFImplPort(WebServiceFeature... features) {
        return super.getPort(GetDettaglioOperatoreCXFImplPort, it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetDettaglioOperatore.class, features);
    }

}
