/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu May 19 09:17:03 CEST 2022
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://opessan.opessanws.def.csi.it/", name = "GetDettaglioOperatore")
@XmlSeeAlso({it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.common.response.ObjectFactory.class,it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.common.request.ObjectFactory.class,ObjectFactory.class})
public interface GetDettaglioOperatore {

    @WebMethod
    @RequestWrapper(localName = "getInfoOperatoreConf", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConf")
    @ResponseWrapper(localName = "getInfoOperatoreConfResponse", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConfResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConfResponse.Return getInfoOperatoreConf(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConf.Arg0 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getInfoOperatore", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatore")
    @ResponseWrapper(localName = "getInfoOperatoreResponse", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreResponse.Return getInfoOperatore(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatore.Arg0 arg0
    );
}
