
/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu May 19 09:17:03 CEST 2022
 * Generated source version: 2.2.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "GetDettaglioOperatore",
                      portName = "GetDettaglioOperatoreCXFImplPort",
                      targetNamespace = "http://opessan.opessanws.services.csi.it/",
                      wsdlLocation = "https://tst-applogic.reteunitaria.piemonte.it:1449/opessanwsj/services/getDettaglioOperatoreUserTkn?wsdl",
                      endpointInterface = "it.csi.def.opessanws.opessan.GetDettaglioOperatore")
                      
public class GetDettaglioOperatoreImpl implements GetDettaglioOperatore {

    private static final Logger LOG = Logger.getLogger(GetDettaglioOperatoreImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.def.opessanws.opessan.GetDettaglioOperatore#getInfoOperatoreConf(it.csi.def.opessanws.opessan.GetInfoOperatoreConf.Arg0  arg0 )*
     */
    public it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConfResponse.Return getInfoOperatoreConf(it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConf.Arg0 arg0) { 
        LOG.info("Executing operation getInfoOperatoreConf");
        System.out.println(arg0);
        try {
        	it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreConfResponse.Return _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.csi.def.opessanws.opessan.GetDettaglioOperatore#getInfoOperatore(it.csi.def.opessanws.opessan.GetInfoOperatore.Arg0  arg0 )*
     */
    public it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreResponse.Return getInfoOperatore(it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatore.Arg0 arg0) { 
        LOG.info("Executing operation getInfoOperatore");
        System.out.println(arg0);
        try {
        	it.csi.solconfig.configuratoreweb.wsdl.opessanDettaglioOperatore.GetInfoOperatoreResponse.Return _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
