/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.solconfig.configuratoreweb.wsdl.opessan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-03-30T09:59:25.078+02:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://opessan.opessanws.def.csi.it/", name = "RicercaOperatore")
@XmlSeeAlso({it.csi.solconfig.configuratoreweb.wsdl.opessan.common.response.ObjectFactory.class, it.csi.solconfig.configuratoreweb.wsdl.opessan.common.request.ObjectFactory.class, ObjectFactory.class})
public interface RicercaOperatore {

    @WebMethod
    @RequestWrapper(localName = "getOperatoreAttivo", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.solconfig.configuratoreweb.wsdl.opessan.GetOperatoreAttivo")
    @ResponseWrapper(localName = "getOperatoreAttivoResponse", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.solconfig.configuratoreweb.wsdl.opessan.GetOperatoreAttivoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public GetOperatoreAttivoResponse.Return getOperatoreAttivo(

        @WebParam(name = "arg0", targetNamespace = "")
                RicercaOperatore_Type arg0
    );
}
