
/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.opessan;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-03-30T09:59:25.061+02:00
 * Generated source version: 3.4.3
 *
 */

@javax.jws.WebService(
                      serviceName = "RicercaOperatore",
                      portName = "RicercaOperatore",
                      targetNamespace = "http://opessan.opessanws.services.csi.it/",
                      wsdlLocation = "https://tst-applogic.reteunitaria.piemonte.it:1449/opessanwsj/services/ricercaOperatoreUserTkn?wsdl",
                      endpointInterface = "it.csi.solconfig.configuratoreweb.wsdl.opessan.RicercaOperatore")

public class RicercaOperatoreImpl implements RicercaOperatore {

    private static final Logger LOG = Logger.getLogger(RicercaOperatoreImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.solconfig.configuratoreweb.wsdl.opessan.RicercaOperatore#getOperatoreAttivo(it.csi.solconfig.configuratoreweb.wsdl.opessan.RicercaOperatore_Type arg0)*
     */
    public GetOperatoreAttivoResponse.Return getOperatoreAttivo(RicercaOperatore_Type arg0) {
        LOG.info("Executing operation getOperatoreAttivo");
        System.out.println(arg0);
        try {
            GetOperatoreAttivoResponse.Return _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
