
/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.2.2
 * Fri May 06 17:30:45 CEST 2022
 * Generated source version: 2.2.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "ScreeningEpatiteC",
                      portName = "ScreeningEpatiteCSoap",
                      targetNamespace = "http://ScreeningEpatiteC.central.services.auraws.aura.csi.it",
                      wsdlLocation = "http://10.102.40.77:57772/sanitxens_t3/AURA.WS.ScreeningEpatiteC.cls?wsdl",
                      endpointInterface = "it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.ScreeningEpatiteCSoap")
                      
public class ScreeningEpatiteCSoapImpl implements ScreeningEpatiteCSoap {

    private static final Logger LOG = Logger.getLogger(ScreeningEpatiteCSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.ScreeningEpatiteCSoap#screeningEpatiteC(it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.Request  assistito )*
     */
    public it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.Response screeningEpatiteC(it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.Request assistito) { 
        LOG.info("Executing operation screeningEpatiteC");
        System.out.println(assistito);
        try {
            it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.Response _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
