/*
* SPDX-FileCopyrightText: (C) Copyright 2022Regione Piemonte
* 
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Fri May 06 17:30:45 CEST 2022
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://ScreeningEpatiteC.central.services.auraws.aura.csi.it", name = "ScreeningEpatiteCSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ScreeningEpatiteCSoap {

    @WebMethod(operationName = "ScreeningEpatiteC", action = "http://ScreeningEpatiteC.central.services.auraws.aura.csi.it/AURA.WS.ScreeningEpatiteC")
    @RequestWrapper(localName = "ScreeningEpatiteC", targetNamespace = "http://ScreeningEpatiteC.central.services.auraws.aura.csi.it", className = "it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.ScreeningEpatiteC")
    @ResponseWrapper(localName = "ScreeningEpatiteCResponse", targetNamespace = "http://ScreeningEpatiteC.central.services.auraws.aura.csi.it", className = "it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.ScreeningEpatiteCResponse")
    @WebResult(name = "ScreeningEpatiteCResult", targetNamespace = "http://ScreeningEpatiteC.central.services.auraws.aura.csi.it")
    public it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.Response screeningEpatiteC(
        @WebParam(name = "assistito", targetNamespace = "http://ScreeningEpatiteC.central.services.auraws.aura.csi.it")
        it.csi.solconfig.configuratoreweb.wsdl.aura.ScreeningEpatiteC.Request assistito
    );
}
